<?php

namespace Acme\DesignBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function getPhotosToType($type_id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('p, t')->from('AcmeDesignBundle:Photo', 'p')
            ->leftJoin('p.type', 't')
            ->where('t.id = :type_id')
            ->setParameter('type_id', $type_id);

        $query = $qb->getQuery();

        return $query->getResult();
    }
}