<?php

namespace Acme\DesignBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeObjectRepository extends EntityRepository
{
}