<?php

namespace Acme\DesignBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePhotoRepository extends EntityRepository
{
    public function getNotEmptyPhotoTypes()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('t, p')->from('AcmeDesignBundle:TypePhoto', 't')
            ->leftJoin('t.photos', 'p')
            ->where('p.id != :null')
            ->setParameter('null', 'NULL');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}